[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "approved-letters"
  dataDirectory = "src/site/_data"

 [[redirects]]
 from = "/:slug/dynamic/"
 to = "/.netlify/functions/dynamic"
 status = 200
 force = true
 _generated_by_eleventy_serverless = "dynamic"

 [[redirects]]
 from = "/:slug/"
 to = "/.netlify/functions/serverless"
 status = 200
 force = true
 _generated_by_eleventy_serverless = "serverless"
