[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "approved-letters"
  dataDirectory = "src/site/_data"


