[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "ALL"
  dataDirectory = "src/site/_data"

[[redirects]]
from = "/admin/approveletters"
force = true
status = 200
  [redirects.conditions]
  Role = [ "admin", "creator" ]

[[redirects]]
from = "/admin/approveletters"
to = "/pages/notallowed"
force = true
status = 302

# Error Page Redirects
[[redirects]]
from = "/*"
to = "/404"
status = 404