[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"
node_bundler = "esbuild"
external_node_modules = ["@11ty/eleventy", "@11ty/dependency-tree"]
included_files = ["src/functions/serverless/**/*", "src/functions/dynamic/**/*"]

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "approved-letters"
  dataDirectory = "src/site/_data"

[[redirects]]
from = "/pages/writeletters/:slug/dynamic/"
to = "/.netlify/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"

[[redirects]]
from = "/pages/writeletters/:slug/"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
