[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "ALL"
  dataDirectory = "src/site/_data"

# [[redirects]]
# from = "/:slug/dynamic/"
# to = "/.netlify/functions/dynamic"
# status = 200
# force = true
# _generated_by_eleventy_serverless = "dynamic"
#
# [[redirects]]
# from = "/:slug/"
# to = "/.netlify/functions/serverless"
# status = 200
# force = true
# _generated_by_eleventy_serverless = "serverless"

# In this example, visitors whose JWT tokens include the `admin` or
# `editor` role can access the `/admin` path.
[[redirects]]
from = "/admin/*"
to = "/admin/:splat"
force = true
status = 200
conditions = {App_metadata = {Role = ["admin", "creator"]}}

#"app_metadata": {"roles": ["investigator", "photographer"]}

#[[redirects]]
#from = "/admin/*"
#to = "/pages/notallowed"
#status = 302
#force = true

# Error Page Redirects
[[redirects]]
from = "/*"
to = "/404"
status = 404