[build]
    command = "npm run build"
    publish = "dist"
    environment = { NODE_VERSION = "18.12.1" } 
    
[functions]
  directory = "src/functions"

# Config for the Netlify Build Plugin: netlify-plugin-form-submissions
[[plugins]]
    package = "netlify-plugin-form-submissions"

[plugins.inputs]
    formNames = "approved-letters"
    dataDirectory = "src/site/_data"
    
