[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "ALL"
  dataDirectory = "src/site/_data"

# In this example, visitors whose JWT tokens include the `admin` or
# `editor` role can access the `/admin` path.
[[redirects]]
from = "/admin/approveletters"
to = "/admin/:splat"
force = true
status = 200
  [redirects.conditions]
  Role = [ "admin", "creator" ]

#"app_metadata": {"roles": ["investigator", "photographer"]}
[[redirects]]
from = "/admin/approveletters"
to = "/pages/notallowed"
force = true
status = 302

# Error Page Redirects
[[redirects]]
from = "/*"
to = "/404"
status = 404