[build]
command = "npm run build"
publish = "dist"

  [build.environment]
  NODE_VERSION = "18.12.1"

[functions]
directory = "src/functions"

[[plugins]]
package = "netlify-plugin-form-submissions"

  [plugins.inputs]
  formNames = "approved-letters"
  dataDirectory = "src/site/_data"

[[redirects]]
from = "/pages/writeletters/:slug/"
to = "/src/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/pages/writeletters/:slug/dynamic/"
to = "/src/functions/dynamic"
status = 200
force = true
_generated_by_eleventy_serverless = "dynamic"
